about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('site/', views.AboutSiteView.as_view(), name='site'),
]

api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('ingredients/', views.get_ingredients, name='get_ingredients'),
    path('subscriptions', views.add_subscription, name='add_subscription'),
    path('subscriptions/<int:id>/', views.remove_subscription, name='remove_subscription'),
    path('favorites', views.add_favorite, name='add_favorite'),
    path('favorites/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('purchases', views.add_purchase, name='add_purchases'),
    path('purchases/<int:id>/', views.remove_purchase, name='remove_purchases'),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('api.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Наименование ингредиента'
    )
    dimension = models.CharField(
        max_length=20,
        verbose_name='Единица измерения'
    )
    
    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        constraints = [
            models.UniqueConstraint(
                fields=('title', 'dimension',),
                name='unique_ingredient'
            ),
        ]

    def __str__(self):
        return f'{self.title} ({self.dimension}.)'


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор рецепта'
    )
    name = models.CharField(
        max_length=250,
        verbose_name='Название рецепта'
    )
    image = models.ImageField(
        upload_to='recipes/',
        verbose_name='Изображение'
    )
    description = models.CharField(
        max_length=3000,
        verbose_name='Описание рецепта'
    )
    ingredients = models.ManyToManyField(
        'Ingredient',
        through='IngredientQuantity',
        through_fields=('recipe', 'ingredient'),
        related_name='recipes',
        verbose_name='Ингредиент'
    )
    tags = models.ManyToManyField(
        'Tag',
        related_name='recipes',
        verbose_name='Tэг'
    )
    cook_time = models.PositiveSmallIntegerField(
        verbose_name='Время приготовления, мин'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.name


class IngredientQuantity(models.Model):
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        'Ingredient',
        on_delete=models.CASCADE,
        verbose_name='Ингредиент'
    )
    quantity = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Количество'
    )
    
    class Meta:
        verbose_name = 'Количество ингредиента в рецепте'
        verbose_name_plural = 'Количество ингредиентов в рецептах'
    
    def __str__(self):
        return f'Количество {self.ingredient} в рецепте"{self.recipe}"'

     
class FavoriteRecipe(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorite_recipes',
        verbose_name='Пользователь',
        db_index=False
    )
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name='favorite_recipes',
        verbose_name='Рецепт',
        db_index=False
    )

    class Meta:
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'recipe',),
                name='unique_favorite_recipe'
            ),
        ]

    def __str__(self):
        return f'Избранный рецепт ({self.user})'


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Пользователь',
        db_index=False
    )
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Рецепт',
        db_index=False
    )

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'recipe',),
                name='unique_purchase'
            ),
        ]

    def __str__(self):
        return f'Покупка ({self.user})'
    
    
class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        db_index=False
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Интересный автор',
        db_index=False
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='unique_subscription'
            ),
        ]

    def __str__(self):
        return f'Подписка ({self.user})'


class TagName(models.TextChoices):
        BREAKFAST = 'breakfast', 'завтрак'
        DINNER = 'dinner', 'обед'
        SUPPER = 'supper', 'ужин' 


class TagColor(models.TextChoices):
        BREAKFAST = 'orange'
        DINNER = 'green'
        SUPPER = 'purple'


class Tag(models.Model):
    name = models.CharField(
        max_length = 20,
        unique=True,
        choices=TagName.choices,
        verbose_name='Тэг',
    )
    color = models.CharField(
        max_length = 20,
        unique=True,
        choices=TagColor.choices,
        verbose_name='Цвет тэга в шаблоне',
    )

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
        
    def __str__(self):
        return self.name
    

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'about:site' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/includes/minicard_recipe.html
<div class="card-list">
    {% for recipe in page %}
    <div class="card" data-id="{{ recipe.id }}">
        <a href="{% url 'recipe' recipe.author recipe.id %}" class="link" target="_blank"><img src="{{ recipe.image.url }}" alt="Здесь должна быть картинка" class="card__image"></a>
        <div class="card__body">
            <a class="card__title link" href="{% url 'recipe' recipe.author recipe.id %}" target="_blank">{{ recipe.name }}</a>
            <ul class="card__items">
                {% for tag in recipe.tags.all %}
                <li class="card__item"><span class="badge badge_style_{{tag.color}}">{{tag.get_name_display}}</span></li>
                {% endfor %}
            </ul>
            <div class="card__items card__items_column">
                <p class="card__text"><span class="icon-time"></span> {{ recipe.cook_time }}</p>
                <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author %}" style="color: black">{% if recipe.author.get_full_name %}{{recipe.author.get_full_name}}{% else %}{{recipe.author.username}}{% endif %}</a></p>
            </div>
        </div>
        {% if user.is_authenticated %}
        {% csrf_token %}
            <div class="card__footer">
                {% if recipe in purchases %}
                    <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
                {% else %}
                    <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
                {% endif %}
                {% if recipe in favorite_recipes %}
                    <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
                {% else %}
                    <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
                {% endif %}
            </div>
        {% endif %}            
    </div>
    {% endfor %}
</div>  

templates/includes/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% if user.is_authenticated %}
        <ul class="nav__items list">
            <li class="nav__item {% if indx %} nav__item_active {% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            <li class="nav__item {% if follow %} nav__item_active {% endif %}"><a href="{% url 'my_subscriptions' %}" class="nav__link link">Мои подписки</a></li>
            <li class="nav__item {% if new %} nav__item_active {% endif %}"><a href="{% url 'new_recipe' %}" class="nav__link link">{% if is_edit %}Редактировать{% else %}Создать{% endif %} рецепт</a></li>
            <li class="nav__item {% if favorite %} nav__item_active {% endif %}"><a href="{% url 'favorite_recipes' %}" class="nav__link link">Избранное</a></li>
            <li class="nav__item {% if purchase %} nav__item_active {% endif %}"><a href="{% url 'my_purchases' %}" class="nav__link link">Список покупок</a>  <span class="badge badge_style_blue nav__badge" id="counter">{% if purchases > 0 %}{{ purchases }}{% endif %}</span></li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
            <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        </ul>
        {% else %}
        <ul class="nav__items list">
            <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/includes/paginator.html
{% load user_filters %}
{% if page.paginator.num_pages > 1 %}
    <nav class="pagination" aria-label="Search results pages">
        <ul class="pagination__container">
            {% if page.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=page.previous_page_number %}"><span class="icon-left"></span></a></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page.number == i %}
                    <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="#">{{ i }}</a></li>
                {% else %}
                    <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=i  %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?{% url_replace page=page.next_page_number %}"><span class="icon-right"></span></a></li>
            {% endif%}
        </ul>
    </nav>
{% endif%}

templates/includes/tags.html
{% load user_filters %}
<ul class="tags">
    {% with tag_values=request.GET|get_tags %}
        {% for tag in tags %}
            <li class="tags__item">
                <a
                    id="{{tag.name}}"
                    class="tags__checkbox tags__checkbox_style_{{tag.color}} {% if tag.name in tag_values or 'tags' not in request.get_full_path %} tags__checkbox_active {% endif %}"
                    href="{{ request.path }}?{{ request|create_tag_link:tag }}">
                </a>
                <span class="tags__label">{{tag.get_name_display|capfirst}}</span>
            </li>
        {% endfor %}
    {% endwith %}
</ul>