api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('ingredients/', views.get_ingredients, name='get_ingredients'),
    path('subscriptions', views.add_subscription, name='add_subscription'),
    path('subscriptions/<int:id>/', views.remove_subscription, name='remove_subscription'),
    path('favorites', views.add_favorite, name='add_favorite'),
    path('favorites/<int:id>/', views.remove_favorite, name='remove_favorite'),
    path('purchases', views.add_purchase, name='add_purchases'),
    path('purchases/<int:id>/', views.remove_purchase, name='remove_purchases'),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('api.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    

recipes/urls.py
from django.urls import path

from . import views
from .proccessors.get_pdf import generate_pdf


urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/new/', views.new_recipe, name='new_recipe'),
    path(
        'recipe/<str:username>/<int:recipe_id>/',
        views.recipe_view,
        name='recipe'
    ),
    path(
        'recipe/<str:username>/<int:recipe_id>/edit/',
        views.recipe_edit,
        name='recipe_edit'
    ),
    path(
        'recipe/<str:username>/<int:id>/delete/',
        views.delete_recipe,
        name='recipe_delete'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('recipe/favorite/', views.favorite_recipes, name='favorite_recipes'),
    path('my-subscriptions/', views.subscriptions, name='my_subscriptions'),
    path('my-purchases/', views.purchases, name='my_purchases'),
    path(
        'purchase/<str:username>/<int:id>/delete/',
        views.delete_purchase,
        name='purchase_delete'
    ),
    path('generate_pdf/', generate_pdf, name='generate_pdf'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Наименование ингредиента'
    )
    dimension = models.CharField(
        max_length=20,
        verbose_name='Единица измерения'
    )
    
    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'
        constraints = [
            models.UniqueConstraint(
                fields=('title', 'dimension',),
                name='unique_ingredient'
            ),
        ]

    def __str__(self):
        return f'{self.title} ({self.dimension}.)'


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор рецепта'
    )
    name = models.CharField(
        max_length=250,
        verbose_name='Название рецепта'
    )
    image = models.ImageField(
        upload_to='recipes/',
        verbose_name='Изображение'
    )
    description = models.CharField(
        max_length=3000,
        verbose_name='Описание рецепта'
    )
    ingredients = models.ManyToManyField(
        'Ingredient',
        through='IngredientQuantity',
        through_fields=('recipe', 'ingredient'),
        related_name='recipes',
        verbose_name='Ингредиент'
    )
    tags = models.ManyToManyField(
        'Tag',
        related_name='recipes',
        verbose_name='Tэг'
    )
    cook_time = models.PositiveSmallIntegerField(
        verbose_name='Время приготовления, мин'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.name


class IngredientQuantity(models.Model):
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        'Ingredient',
        on_delete=models.CASCADE,
        verbose_name='Ингредиент'
    )
    quantity = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name='Количество'
    )
    
    class Meta:
        verbose_name = 'Количество ингредиента в рецепте'
        verbose_name_plural = 'Количество ингредиентов в рецептах'
    
    def __str__(self):
        return f'Количество {self.ingredient} в рецепте"{self.recipe}"'

     
class FavoriteRecipe(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorite_recipes',
        verbose_name='Пользователь',
        db_index=False
    )
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name='favorite_recipes',
        verbose_name='Рецепт',
        db_index=False
    )

    class Meta:
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'recipe',),
                name='unique_favorite_recipe'
            ),
        ]

    def __str__(self):
        return f'Избранный рецепт ({self.user})'


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Пользователь',
        db_index=False
    )
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Рецепт',
        db_index=False
    )

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'recipe',),
                name='unique_purchase'
            ),
        ]

    def __str__(self):
        return f'Покупка ({self.user})'
    
    
class Subscription(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        db_index=False
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Интересный автор',
        db_index=False
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='unique_subscription'
            ),
        ]

    def __str__(self):
        return f'Подписка ({self.user})'


class TagName(models.TextChoices):
        BREAKFAST = 'breakfast', 'завтрак'
        DINNER = 'dinner', 'обед'
        SUPPER = 'supper', 'ужин' 


class TagColor(models.TextChoices):
        BREAKFAST = 'orange'
        DINNER = 'green'
        SUPPER = 'purple'


class Tag(models.Model):
    name = models.CharField(
        max_length = 20,
        unique=True,
        choices=TagName.choices,
        verbose_name='Тэг',
    )
    color = models.CharField(
        max_length = 20,
        unique=True,
        choices=TagColor.choices,
        verbose_name='Цвет тэга в шаблоне',
    )

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
        
    def __str__(self):
        return self.name
    

recipes/forms.py
from django.forms import ModelForm, Textarea

from .models import Recipe

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = (
            'name',
            'cook_time',
            'description',
            'image',
        )
        labels = {
            'name': 'Название рецепта',
            'tag': 'Tэги',
            'cook_time': 'Время приготовления',
            'description': 'Описание',
            'image': 'Загрузить фото',
        }
        widgets = {
            'description': Textarea(attrs={
                'name': 'description',
                'id': 'id_description',
                'rows': '8',
                'class': 'form__textarea'
            })
        }
        

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Title{% endblock %}</title>
    {% block style %}{% endblock %}    
</head>
<body class="body">
<header class="header">
    {% if user.is_authenticated %}
        {% include "includes/nav.html" with purchases=num_purchases %}
    {% else %}
        {% include "includes/nav.html" %}
    {% endif %}
</header>
    <main class="main container">
        {% block content %}{% endblock %}
    </main>
    {% include "includes/footer.html" %}
{% block js %}{% endblock %}
</body>
</html>

templates/favorite.html
{% extends "base.html" %}

{% block title %}Избранное{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}

{% block content %}
    {% load user_filters %}
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
                {% include 'includes/tags.html' with tags=tags %}
        </div>
        
        {% include 'includes/minicard_recipe.html' with page=page favorite_recipes=favorite_recipes purchases=purchases %}

    {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}
{% block js %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Рецепты{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}

{% block content %}
    {% load user_filters %}
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include 'includes/tags.html' with tags=tags %}
        </div>
        
        {% include 'includes/minicard_recipe.html' with page=page favorite_recipes=favorite_recipes purchases=purchases %}

    {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'indexAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock %}

templates/new_recipe.html
{% extends "base.html" %}

{% block title %}{% if is_edit %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'pages/form.css' %}">{% endblock %}

{% block content %}
    {% load user_filters %}

        {% if next %}
            <div class="custom-center-block">
                <p class="custom-text-block">Вы обратились к странице, доступ к которой возможен только для залогиненных пользователей. Пожалуйста, авторизуйтесь.</p>
            </div>          
        {% endif %}

        <div class="main__header">
            <h1 class="main__title">{% if is_edit %}Редактирование рецепта{% else %}Создание рецепта{% endif %}</h1>
        </div>
        <div class="form-container">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                    <label for="id_name" class="form__label">{{form.name.label}}</label>
                    <div class="form__field-group">
                        {{ form.name|addclass:"form__input" }}
                        {% if form.errors %}
                            {% for error in form.name.errors %}
                                <span class="form__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <p class="form__label">{{ form.tag.label }}</p>
                    <div class="form__field-group">
                        <div class="tags">
                            {% if tag_or_ingredient_empty or ingredient_error %}
                                {% if not 'tag_empty' in tag_or_ingredient_empty %}
                                    {% for tag in tags %}
                                        <div class="tags__item">
                                            <input type="checkbox" name="{{tag.name}}" id="id_{{tag.pk}}" class="tags__checkbox tags__checkbox_style_{{tag.color}}" {% if tag.name in tags_from_query %} checked {% endif %}>
                                            <label for="id_{{tag.pk}}" class="tags__label">{{tag.get_name_display}}</label>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    {% for tag in tags %}
                                        <div class="tags__item">
                                            <input type="checkbox" name="{{tag.name}}" id="id_{{tag.pk}}" class="tags__checkbox tags__checkbox_style_{{tag.color}}" {% if tag in tags_of_recipe %} checked {% endif %}>
                                            <label for="id_{{tag.pk}}" class="tags__label">{{tag.get_name_display}}</label>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% else %}
                                {% for tag in tags %}
                                    <div class="tags__item">
                                        <input type="checkbox" name="{{tag.name}}" id="id_{{tag.pk}}" class="tags__checkbox tags__checkbox_style_{{tag.color}}" {% if tag in tags_of_recipe %} checked {% endif %}>
                                        <label for="id_{{tag.pk}}" class="tags__label">{{tag.get_name_display}}</label>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        {% if 'tag_empty' in tag_or_ingredient_empty %}
                            <span class="form__error">Добавьте тэги</span>
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <label for="nameIngredient" class="form__label">Ингредиенты</label>
                    <div class="form__field-group">
                        <div class="form__field-group-ingredientes">
                            <div class="form__dropdown">
                                <input type="text" id="nameIngredient" class="form__input">
                                <div class="form__dropdown-items">
                                </div>
                            </div>
                            <input type="number" id="cantidad" class="form__input" min="0">
                            <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        </div>                      
                            <div class="form__field-group-ingredientes-container">
                                {% if tag_or_ingredient_empty %}
                                    {% if not 'ingredient_empty' in tag_or_ingredient_empty %}
                                        {% for title, value_list in ingredients_from_query.items %}
                                            <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}"><span>{{title}} {{value_list.0}}{{value_list.1}}</span> <span class="form__field-item-delete"></span>
                                                <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{title}}">
                                                <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{value_list.0}}">
                                                <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{value_list.1}}">
                                            </div>
                                        {% endfor %}
                                    {% endif %}                              
                                {% elif ingredient_error %}
                                    {% for each in ingredients_from_query %}
                                        <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}"><span>{{each.ingredient.title}} {{each.quantity}} {{each.ingredient.dimension}}.</span> <span class="form__field-item-delete"></span>
                                            <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{each.ingredient.title}}">
                                            <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{each.quantity}}">
                                            <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{each.ingredient.dimension}}">
                                        </div>
                                    {% endfor%}
                                {% else %}
                                    {% if is_edit %}
                                        {% for each in ingredients_of_recipe %}
                                            <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}"><span>{{each.ingredient.title}} {{each.quantity}} {{each.ingredient.dimension}}.</span> <span class="form__field-item-delete"></span>
                                                <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{each.ingredient.title}}">
                                                <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{each.quantity}}">
                                                <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{each.ingredient.dimension}}">
                                            </div>
                                        {% endfor%}
                                    {% endif %}
                                {% endif %}
                            </div>
                        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        {% if 'ingredient_empty' in tag_or_ingredient_empty %}
                            <span class="form__error">Добавьте ингредиенты</span>
                        {% elif ingredient_error %}
                            <span class="form__error">Ошибка ингредиента. Вы попытались добавить:</span>
                                {% for ingredient in unknown_ingredients %}
                                    <span class="form__error">{{ forloop.counter }}. {{ingredient}} - неизвестный ингредиент. Выберите из базы.</span>
                                {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_time" class="form__label">{{ form.cook_time.label }}</label>
                    <div class="form__field-group form__field-group_time">
                        {{ form.cook_time|addclass:"form__input" }}
                        <label for="id_time" class="form__label">минут</label>
                        {% if form.errors %}
                            {% for error in form.cook_time.errors %}
                                <span class="form__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <label for="id_description" class="form__label">{{ form.description.label }}</label>
                    <div class="form__field-group">
                        {{ form.description }}
                        {% if form.errors %}
                            {% for error in form.description.errors %}
                                <span class="form__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__group">
                    <span class="form__label">{{ form.image.label }}</span>
                    <div class="form__field-group">
                        {{ form.image }}
                        {% if form.errors %}
                            {% for error in form.image.errors %}
                                <span class="form__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="form__footer">
                    <button class="button button_style_blue">{% if is_edit %}Сохранить{% else %}Создать рецепт{% endif %}</button> {% if is_edit %}<a style="margin-left: 2.5em" href="{% url 'recipe_delete' request.user.username recipe.id %}" class="form__ingredient-link">Удалить</a>{% endif %}
                </div>
            </form>
        </div>
{% endblock %}
{% block js %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}{% if author.get_full_name %}{{author.get_full_name}}{% else %}{{author.username}}{% endif %}{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock %}

{% block content %}
    {% load user_filters %}
        <div class="main__header">
            <h1 class="main__title">{% if author.get_full_name %}{{author.get_full_name}}{% else %}{{author.username}}{% endif %}</h1>
            {% include 'includes/tags.html' with tags=tags %}
        </div>
    {% if user.is_authenticated and user != author %}         
        <div class="author-subscribe" data-author="{{ author.id }}">
            {% if subscription %}
                <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button></p>
            {% else %}
                <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
            {% endif %}
        </div>
    {% endif %}
        {% include 'includes/minicard_recipe.html' with page=page %}

    {% include 'includes/paginator.html' with page=page paginator=paginator %}
{% endblock %}

{% block js %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>
  <script src="{% static 'js/components/Subscribe.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'authorRecipe.js' %}"></script>
  {% endblock %}

templates/recipe.html
{% extends "base.html" %}

{% block title %}{{recipe.name}}{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'pages/single.css' %}">{% endblock %}
    
{% block content %}
    {% load user_filters %}
        <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
            <img src="{{recipe.image.url}}" alt="Картинка рецепта" class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{recipe.name}}</h1>
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    <div class="single-card__favorite">
                            {% if favorite_recipe %}
                                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
                                <div class="single-card__favorite-tooltip tooltip">Убрать из избранного</div>
                            {% else %}
                                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
                                <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                            {% endif %}          
                    </div>
                    {% endif %}
                </div>
                <ul class="single-card__items">
                    {% for tag in recipe.tags.all %}
                        <li class="single-card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.get_name_display }}</span></li>
                    {% endfor %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{recipe.cook_time}} </p>
                    {% if user == author %}
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span> {% if author.get_full_name %}{{author.get_full_name}}{% else %}{{author.username}}{% endif %}</p></li>
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' request.user.username recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                    </ul>
                    {% endif %}
                    {% if user != author %}
                    <p class="single-card__text"><span class="icon-user"></span>
                        {% if author.get_full_name %}{{author.get_full_name}}{% else %}{{author.username}}{% endif %}
                    </p>
                    {% endif %}
                </div> 
                <ul class="single-card__items">
                    {% if user.is_authenticated %}
                        {% if purchase %}
                            <li class="single-card__item"></li><button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button></li>
                        {% else %}
                            <li class="single-card__item"><button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button></li>
                        {% endif %}
                        {% if user != author %}
                            {% if subscription %}
                                <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться</button></li>
                            {% else %}
                                <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></li>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингредиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for each in recipe.ingredientquantity_set.all %}
                        <p class=" single-card__section-item">{{ each.ingredient.title }} - {{each.quantity}} {{ each.ingredient.dimension }}.</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
                </div>
            </div>
{% endblock %}
{% block js %}
<script src="{% static 'js/components/Purchases.js' %}"></script>
{% if user.is_authenticated %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
{% endif %}
<script src="{% static 'js/config/config.js' %}"></script>

<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
    <script src="{% static 'singlePage.js' %}"></script>
{% else %}
    <script src="{% static 'singlePageNotAuth.js' %}"></script>
{% endif %}
{% endblock %}